### ISSUE TITLE
[App][Bug]: <title>

### ISSUE THREAD

**Issue by tinhojw** [sircharlo/meeting-media-manager#1690]
### What happened?

erro ao abrir a reunião da semana de 3 de abril

### To Reproduce

3. Do '....'

### What did you expect to happen?

esperava abrir a reunião da semana de 3 abril

### Version

v23.3.0

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
{
  "1679249749524": [
    "Cannot read properties of undefined (reading 'DocumentId')"
  ]
}
```

### Additional context

Windows_NT 10.0.19045 x64
### Anonymized `prefs.json`
```
{
  "app": {
    "autoOpenFolderWhenDone": false,
    "autoQuitWhenDone": false,
    "autoRunAtBoot": false,
    "autoStartSync": true,
    "betaUpdates": false,
    "congregationName": "Livramento",
    "customCachePath": null,
    "disableAutoUpdate": false,
    "disableHardwareAcceleration": false,
    "localAppLang": "pt",
    "localOutputPath": "***",
    "obs": {
      "enable": false,
      "port": "4455",
      "password": "***",
      "mediaScene": "MIDIA",
      "cameraScene": "CAMERA",
      "zoomScene": null,
      "useV4": false,
      "imageScene": null
    },
    "offline": false,
    "outputFolderDateFormat": "DD-MM-YYYY - dddd",
    "theme": "system",
    "zoom": {
      "enable": false,
      "name": null,
      "id": null,
      "password": null,
      "spotlight": false,
      "hideComponent": false,
      "autoRename": "***",
      "autoStartMeeting": false,
      "autoStartTime": 1
    }
  },
  "cong": {
    "server": "***",
    "port": "***",
    "user": "***",
    "password": "***",
    "dir": "***"
  },
  "media": {
    "autoPlayFirst": false,
    "autoPlayFirstTime": 5,
    "enableMediaDisplayButton": true,
    "enableMp4Conversion": false,
    "enablePp": false,
    "enableSubtitles": false,
    "enableVlcPlaylistCreation": false,
    "excludeLffImages": true,
    "excludeTh": true,
    "hideMediaLogo": false,
    "hideWinAfterMedia": false,
    "includePrinted": true,
    "keepOriginalsAfterConversion": false,
    "lang": "T",
    "langFallback": null,
    "langSubs": null,
    "langUpdatedLast": "2023-03-06T19:49:35.523Z",
    "maxRes": "720p",
    "mediaWinShortcut": "Alt+Z",
    "ppBackward": null,
    "ppForward": null,
    "preferredOutput": 2779098405,
    "presentShortcut": "Alt+D"
  },
  "meeting": {
    "autoStartMusic": true,
    "enableMusicButton": true,
    "enableMusicFadeOut": true,
    "coWeek": null,
    "musicFadeOutTime": 60,
    "musicFadeOutType": "smart",
    "musicVolume": 20,
    "mwDay": 2,
    "mwStartTime": "19:30",
    "shuffleShortcut": "Alt+K",
    "specialCong": false,
    "weDay": 5,
    "weStartTime": "19:00"
  },
  "excludeLffi": {},
  "excludeLffiImages": {},
  "__internal__": {
    "migrations": {
      "version": "23.3.0"
    }
  }
}
```
### Error details
```
{
  "stack": "TypeError: Cannot read properties of undefined (reading 'DocumentId')\n    at f.<anonymous> (app://./_nuxt/8b976cd.js:1:443249)\n    at async f.getMwMedia (app://./_nuxt/0acbc25.js:1:19527)\n    at async Promise.allSettled (index 0)\n    at async f.startMediaSync (app://./_nuxt/0acbc25.js:1:22194)",
  "message": "Cannot read properties of undefined (reading 'DocumentId')",
  "__sentry_captured__": true
}
```

**Comment by mtdvlpr** [comment]
Fix has been implemented and will be in the next release
