### ISSUE TITLE
[Bug]: Unable to fetch media Watchtower video on Sign Languages

### ISSUE THREAD

**Issue by vbastianpc** [sircharlo/meeting-media-manager#1853]
### What happened?

Can't download Watchtower video for sign languages. I think that GETPUBMEDIALINKS missing parameter `issue`.

Instead of
```
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?pub=w&track=4&langwritten=ASL&output=json
```
it should be
```
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?pub=w&issue=20230300&track=4&langwritten=ASL&output=json
```

<img width="916" alt="Captura de pantalla 2023-05-21 a la(s) 12 43 36" src="https://github.com/sircharlo/meeting-media-manager/assets/34177793/d04c7401-abc7-479a-819a-0554de94b8f5">
<img width="763" alt="Captura de pantalla 2023-05-21 a la(s) 13 07 17" src="https://github.com/sircharlo/meeting-media-manager/assets/34177793/e15fd340-b969-488e-bd05-b3c4e9f6f3d1">

### To Reproduce

1. Set American Sign Language (or any sign language) on Media Setup.
2. Click on Update Media Folders.
3. See 2 warnings and 1 error.

### What did you expect to happen?

Fetch watchtower video for sign languages.

### Version

v23.4.2

### What platform are you seeing the problem on?

MacOS

### Relevant log output

```shell
{
  "1684687702562": [
    "Request failed with status code 400"
  ],
  "1684687702577": [
    "Request failed with status code 400"
  ],
  "1684687702580": [
    "No WE songs found!"
  ]
}
```

### Additional context

Darwin 22.4.0 arm64
### Anonymized `prefs.json`
```
{
  "app": {
    "autoOpenFolderWhenDone": false,
    "autoQuitWhenDone": false,
    "autoRunAtBoot": false,
    "autoStartSync": false,
    "betaUpdates": false,
    "congregationName": "Señas",
    "customCachePath": null,
    "disableAutoUpdate": false,
    "disableHardwareAcceleration": false,
    "localAppLang": "en",
    "localOutputPath": "***",
    "obs": {
      "enable": false,
      "port": null,
      "password": null,
      "mediaScene": null,
      "imageScene": null,
      "cameraScene": null,
      "zoomScene": null,
      "useV4": false
    },
    "offline": false,
    "outputFolderDateFormat": "YYYY-MM-DD",
    "theme": "system",
    "zoom": {
      "enable": false,
      "name": null,
      "id": null,
      "password": null,
      "spotlight": false,
      "hideComponent": false,
      "autoRename": "***",
      "autoStartMeeting": false,
      "autoStartTime": 1
    }
  },
  "cong": {
    "server": null,
    "port": null,
    "password": null,
    "dir": null,
    "enable": false,
    "username": null,
    "user": null
  },
  "media": {
    "autoPlayFirst": false,
    "autoPlayFirstTime": 5,
    "enableMediaDisplayButton": true,
    "enableMp4Conversion": false,
    "enablePp": false,
    "enableSubtitles": false,
    "enableVlcPlaylistCreation": false,
    "excludeLffImages": false,
    "excludeTh": false,
    "hideMediaLogo": false,
    "hideWinAfterMedia": false,
    "includePrinted": false,
    "keepOriginalsAfterConversion": false,
    "lang": "ASL",
    "langFallback": null,
    "langSubs": null,
    "langUpdatedLast": "2023-05-21T16:34:57.773Z",
    "maxRes": "720p",
    "mediaWinShortcut": "Alt+Z",
    "ppBackward": null,
    "ppForward": null,
    "preferredOutput": "window",
    "presentShortcut": "Alt+D"
  },
  "meeting": {
    "autoStartMusic": false,
    "enableMusicButton": false,
    "enableMusicFadeOut": false,
    "coWeek": null,
    "musicFadeOutTime": 5,
    "musicFadeOutType": "smart",
    "musicVolume": 100,
    "mwDay": 2,
    "mwStartTime": "19:00",
    "shuffleShortcut": "Alt+K",
    "specialCong": false,
    "weDay": 6,
    "weStartTime": "18:00"
  },
  "__internal__": {
    "migrations": {
      "version": "23.4.2"
    }
  }
}
```
### Error details
```
{
  "stack": "Error: No WE songs found!\n    at app://./_nuxt/dc4caa5.js:1:450218\n    at async Promise.allSettled (index 5)\n    at async f.<anonymous> (app://./_nuxt/dc4caa5.js:1:450265)\n    at async f.getWeMedia (app://./_nuxt/f788b98.js:1:23328)\n    at async Promise.allSettled (index 1)\n    at async f.startMediaSync (app://./_nuxt/f788b98.js:1:25367)",
  "message": "No WE songs found!",
  "__sentry_captured__": true
}
```

**Comment by mtdvlpr** [comment]
Hi @vbastianpc, thanks for reporting this bug! I've fixed it and it will be released shortly.

**Comment by vbastianpc** [comment]
Wow! Thank you very much for fixing it so quickly. I would like to say thank you for this application. All the effort and time that you dedicate allows the Audio/Video work to be easier. We are several speaking and sign language congregations that use M3. During the meeting it allows us to be focused on teaching without distractions.
