### ISSUE TITLE
[App][Bug]: Media from tracts not being loaded properly

### ISSUE THREAD

**Issue by kleyfurlan** [sircharlo/meeting-media-manager#2034]
### What happened?

nao sei como descrever o bug

### To Reproduce

3. Do '....'

### What did you expect to happen?

nao sei como descrever o bug

### Version

v23.5.0

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
{}
```

### Screenshots

{}

### Additional context

Windows_NT 10.0.19045 x64
### Anonymized `prefs.json`
```
{
  "app": {
    "autoOpenFolderWhenDone": false,
    "autoQuitWhenDone": false,
    "autoRunAtBoot": true,
    "autoStartSync": true,
    "betaUpdates": false,
    "congregationName": "Echaporã",
    "customCachePath": "***",
    "disableAutoUpdate": false,
    "disableHardwareAcceleration": false,
    "localAppLang": "pt",
    "localOutputPath": "***",
    "obs": {
      "enable": true,
      "port": "4455",
      "password": "***",
      "mediaScene": "Midias",
      "imageScene": null,
      "cameraScene": "Palco",
      "zoomScene": null,
      "useV4": false
    },
    "offline": false,
    "outputFolderDateFormat": "DD-MM-YYYY - dddd",
    "theme": "system",
    "zoom": {
      "enable": false,
      "name": null,
      "id": null,
      "password": null,
      "spotlight": false,
      "hideComponent": false,
      "autoRename": "***",
      "autoStartMeeting": false,
      "autoStartTime": 1
    }
  },
  "cong": {
    "server": "***",
    "port": "***",
    "user": "***",
    "password": "***",
    "dir": "***"
  },
  "media": {
    "autoPlayFirst": false,
    "autoPlayFirstTime": 5,
    "enableMediaDisplayButton": true,
    "enableMp4Conversion": false,
    "enablePp": false,
    "enableSubtitles": false,
    "enableVlcPlaylistCreation": false,
    "excludeLffImages": true,
    "excludeTh": true,
    "excludeFootnotes": true,
    "hideMediaLogo": false,
    "hideWinAfterMedia": false,
    "includePrinted": true,
    "keepOriginalsAfterConversion": false,
    "lang": "T",
    "langFallback": null,
    "langSubs": null,
    "langUpdatedLast": "2023-07-10T22:25:10.277Z",
    "maxRes": "720p",
    "mediaWinShortcut": "Alt+Z",
    "ppBackward": null,
    "ppForward": null,
    "preferredOutput": "window",
    "presentShortcut": "Alt+D"
  },
  "meeting": {
    "autoStartMusic": true,
    "enableMusicButton": true,
    "enableMusicFadeOut": true,
    "coWeek": null,
    "musicFadeOutTime": 60,
    "musicFadeOutType": "smart",
    "musicVolume": 15,
    "mwDay": 2,
    "mwStartTime": "19:30",
    "shuffleShortcut": "Alt+K",
    "specialCong": false,
    "weDay": 5,
    "weStartTime": "19:00"
  },
  "__internal__": {
    "migrations": {
      "version": "23.5.0"
    }
  }
}
```
### Error details
```
{
  "stack": "Error: ENOENT: no such file or directory, stat 'C:/Users/Salão do Reino/Documents/Midias/Cache/Publications/T/T-/0/0/1102013410_univ_cnt_1.jpg'\n    at statSync (node:fs:1615:3)\n    at t.statSync (node:electron/js2c/asar_bundle:2:4510)\n    at app://./_nuxt/e282221.js:5:799626\n    at app://./_nuxt/a5472b7.js:1:442364\n    at async Promise.allSettled (index 0)\n    at async R (app://./_nuxt/a5472b7.js:1:442493)\n    at async app://./_nuxt/a5472b7.js:1:436576\n    at async Promise.allSettled (index 1)\n    at async B (app://./_nuxt/a5472b7.js:1:437573)\n    at async f.<anonymous> (app://./_nuxt/a5472b7.js:1:450818)\n    at async f.getMwMedia (app://./_nuxt/035a998.js:1:22657)\n    at async Promise.allSettled (index 0)\n    at async f.startMediaSync (app://./_nuxt/035a998.js:1:25372)\n    at async f.execute (app://./_nuxt/035a998.js:1:20399)",
  "message": "ENOENT: no such file or directory, stat 'C:/Users/Salão do Reino/Documents/Midias/Cache/Publications/T/T-/0/0/1102013410_univ_cnt_1.jpg'",
  "errno": -4058,
  "syscall": "stat",
  "code": "ENOENT",
  "path": "C:/Users/Salão do Reino/Documents/Midias/Cache/Publications/T/T-/0/0/1102013410_univ_cnt_1.jpg"
}
```

**Comment by sircharlo** [comment]
Thanks for reporting this! Fixed in https://github.com/sircharlo/meeting-media-manager/commit/a75376c26cafe6255106e3668820c1bfd9259f5c. Will be released in next update.
