### ISSUE TITLE
Can't collect media for 11/07/23 and week after either

### ISSUE THREAD

**Issue by skimark1** [sircharlo/meeting-media-manager#2232]
### What happened?

I'm going to be gone for a couple of weeks and was trying to collect media for the meetings I won't be at. When I tried to get media for 11/6-11/12 the 11/7 date fails with the error in my screenshot. I tried the week after and got the same error. Please help

### To Reproduce

Select week of 2023-11-06 - 2023-11-12

### What did you expect to happen?

Expected media to be retrieved.

### Version

v23.8.1

### What platform are you seeing the problem on?

MacOS

### Relevant log output

```shell
{
  "1697920945634": [
    "Cannot read properties of undefined (reading 'FeatureTitle')"
  ]
}
```

### Screenshots

<img width="699" alt="Screenshot 2023-10-21 at 2 17 29 PM" src="https://github.com/sircharlo/meeting-media-manager/assets/128306908/f996b0e4-1494-418d-b01f-e3bb011758ff">

### Additional context

Darwin 23.0.0 x64
### Anonymized `prefs.json`
```
{
  "app": {
    "autoOpenFolderWhenDone": false,
    "autoQuitWhenDone": false,
    "autoRunAtBoot": false,
    "autoStartSync": false,
    "betaUpdates": false,
    "congregationName": "Mesa Park",
    "customCachePath": null,
    "disableAutoUpdate": false,
    "disableHardwareAcceleration": false,
    "localAppLang": "en",
    "localOutputPath": "***",
    "obs": {
      "enable": false,
      "port": null,
      "password": null,
      "mediaScene": null,
      "cameraScene": null,
      "useV4": true,
      "zoomScene": null,
      "imageScene": null
    },
    "offline": false,
    "outputFolderDateFormat": "YYYY-MM-DD - dddd",
    "theme": "system",
    "zoom": {
      "enable": false,
      "name": null,
      "id": null,
      "password": null,
      "spotlight": false,
      "hideComponent": false,
      "autoRename": "***",
      "autoStartMeeting": false,
      "autoStartTime": 1
    }
  },
  "cong": {
    "server": null,
    "port": null,
    "user": null,
    "password": null,
    "dir": null
  },
  "media": {
    "autoPlayFirst": false,
    "autoPlayFirstTime": 5,
    "enableMediaDisplayButton": false,
    "enableMp4Conversion": false,
    "enablePp": false,
    "enableSubtitles": false,
    "enableVlcPlaylistCreation": false,
    "excludeLffImages": true,
    "excludeTh": true,
    "excludeFootnotes": true,
    "hideMediaLogo": false,
    "hideWinAfterMedia": false,
    "includePrinted": false,
    "keepOriginalsAfterConversion": false,
    "lang": "E",
    "langFallback": null,
    "langSubs": null,
    "langUpdatedLast": "2023-10-21T20:33:56.827Z",
    "maxRes": "720p",
    "mediaWinShortcut": "Alt+Z",
    "ppBackward": null,
    "ppForward": null,
    "preferredOutput": 441111130,
    "presentShortcut": "Alt+D"
  },
  "meeting": {
    "autoStartMusic": false,
    "enableMusicButton": false,
    "enableMusicFadeOut": false,
    "coWeek": null,
    "musicFadeOutTime": 5,
    "musicFadeOutType": "smart",
    "musicVolume": 100,
    "mwDay": 1,
    "mwStartTime": null,
    "shuffleShortcut": "Alt+K",
    "specialCong": false,
    "weDay": 5,
    "weStartTime": null
  },
  "__internal__": {
    "migrations": {
      "version": "23.8.1"
    }
  }
}
```
### Error details
```
{
  "stack": "TypeError: Cannot read properties of undefined (reading 'FeatureTitle')\n    at f.<anonymous> (app://./_nuxt/ddc7087.js:1:531775)\n    at async f.getMwMedia (app://./_nuxt/6a09ca2.js:1:22657)\n    at async Promise.allSettled (index 0)\n    at async f.startMediaSync (app://./_nuxt/6a09ca2.js:1:25372)",
  "message": "Cannot read properties of undefined (reading 'FeatureTitle')",
  "__sentry_captured__": true
}
```

**Comment by mtdvlpr** [comment]
@skimark1, thank you for reporting! This bug has been resolved in #2233 and will be released later today.

**Comment by skimark1** [comment]
Thanks for producing such a valuable tool for us and for the great support!

**Comment by skimark1** [comment]
I appreciate your hard work on this wonderful tool!
Thanks,
Mark Cillis
***@***.***
