### ISSUE TITLE
Error extracting media for week of 10/14/2024

### ISSUE THREAD

**Issue by skimark1** [sircharlo/meeting-media-manager#2710]
### What happened?

See screenshot. I got 4 errors the first time, re ran it and eventually was left with 1 error

### To Reproduce

Just try to collect media for week beginning 10/12/24

### What did you expect to happen?

Extract all media for meeting

### Version

v24.4.5

### What platform are you seeing the problem on?

MacOS

### Relevant log output

```shell
{}
```

### Screenshots

<img width="701" alt="Screenshot 2024-10-12 at 7 43 41 AM" src="https://github.com/user-attachments/assets/20236368-d112-4a2c-b97d-0b2adda3347a">

### Additional context

Darwin 23.6.0 x64
### Anonymized `prefs.json`
```
{
  "app": {
    "autoOpenFolderWhenDone": false,
    "autoQuitWhenDone": false,
    "autoRunAtBoot": false,
    "autoStartSync": false,
    "betaUpdates": false,
    "congregationName": "Mesa Park",
    "customCachePath": null,
    "disableAutoUpdate": false,
    "disableHardwareAcceleration": false,
    "localAppLang": "en",
    "localOutputPath": "***",
    "obs": {
      "enable": false,
      "port": null,
      "password": null,
      "mediaScene": null,
      "cameraScene": null,
      "useV4": true,
      "zoomScene": null,
      "imageScene": null
    },
    "offline": false,
    "outputFolderDateFormat": "YYYY-MM-DD - dddd",
    "theme": "system",
    "zoom": {
      "enable": false,
      "name": null,
      "id": null,
      "password": null,
      "spotlight": false,
      "hideComponent": false,
      "autoRename": "***",
      "autoStartMeeting": false,
      "autoStartTime": 1
    }
  },
  "cong": {
    "server": null,
    "port": null,
    "user": null,
    "password": null,
    "dir": null
  },
  "media": {
    "autoPlayFirst": false,
    "autoPlayFirstTime": 5,
    "enableMediaDisplayButton": false,
    "enableMp4Conversion": false,
    "enablePp": false,
    "enableSubtitles": false,
    "enableVlcPlaylistCreation": false,
    "excludeLffImages": true,
    "excludeTh": true,
    "excludeFootnotes": true,
    "hideMediaLogo": false,
    "hideWinAfterMedia": false,
    "includePrinted": false,
    "keepOriginalsAfterConversion": false,
    "lang": "E",
    "langFallback": null,
    "langSubs": null,
    "langUpdatedLast": "2024-07-20T19:00:30.352Z",
    "maxRes": "720p",
    "mediaWinShortcut": "Alt+Z",
    "ppBackward": null,
    "ppForward": null,
    "preferredOutput": 441111130,
    "presentShortcut": "Alt+D"
  },
  "meeting": {
    "autoStartMusic": false,
    "enableMusicButton": false,
    "enableMusicFadeOut": false,
    "coWeek": null,
    "musicFadeOutTime": 5,
    "musicFadeOutType": "smart",
    "musicVolume": 100,
    "mwDay": 1,
    "mwStartTime": null,
    "shuffleShortcut": "Alt+K",
    "specialCong": false,
    "weDay": 6,
    "weStartTime": null
  },
  "__internal__": {
    "migrations": {
      "version": "24.4.5"
    }
  }
}
```
### Error details
```
{
  "stack": "Error: ENOENT: no such file or directory, stat '/Users/skimark/Library/Application Support/meeting-media-manager/Publications/E/w/20120901/0/2012645_univ_cnt_1.jpg'\n    at Object.stat (node:internal/fs/sync:58:25)\n    at statSync (node:fs:1669:17)\n    at t.statSync (node:electron/js2c/node_init:2:5052)\n    at app://./_nuxt/d22519d.js:5:800816\n    at app://./_nuxt/21b8067.js:1:118101\n    at async Promise.allSettled (index 0)\n    at async R (app://./_nuxt/21b8067.js:1:118230)\n    at async app://./_nuxt/21b8067.js:1:112125\n    at async Promise.allSettled (index 1)\n    at async B (app://./_nuxt/21b8067.js:1:113122)\n    at async f.<anonymous> (app://./_nuxt/21b8067.js:1:126931)\n    at async f.getMwMedia (app://./_nuxt/250c642.js:1:38777)\n    at async Promise.allSettled (index 0)\n    at async f.startMediaSync (app://./_nuxt/250c642.js:1:41492)",
  "message": "ENOENT: no such file or directory, stat '/Users/skimark/Library/Application Support/meeting-media-manager/Publications/E/w/20120901/0/2012645_univ_cnt_1.jpg'",
  "errno": -2,
  "code": "ENOENT",
  "syscall": "stat",
  "path": "/Users/skimark/Library/Application Support/meeting-media-manager/Publications/E/w/20120901/0/2012645_univ_cnt_1.jpg"
}
```

**Comment by mtdvlpr** [comment]
Fixed in #2711 and will be released soon as `v24.4.6`.
