### ISSUE TITLE
[BUG] Adding a song

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#441]
### Describe the bug
I was trying to add a song to the media using the song picker. Then it gave an error when trying to add any song. It might be related to the fact that it is for a sign language.

### To Reproduce
1. Go to 'a date'
2. Click on 'song'
3. Do 'select a song to add'

### Screenshots
If possible, add screenshots to help explain your problem.

### System specs
- Linux 5.15.0-46-generic
- M³ v22.8.0

### Anonymized `prefs.json`
```
{
  "autoOpenFolderWhenDone": null,
  "autoQuitWhenDone": null,
  "autoRunAtBoot": null,
  "autoStartSync": null,
  "congServer": null,
  "congServerDir": null,
  "congServerPass": null,
  "congServerPort": null,
  "congServerUser": null,
  "congregationName": "***",
  "disableHardwareAcceleration": null,
  "enableMediaDisplayButton": true,
  "enableMp4Conversion": null,
  "enableMusicButton": null,
  "enableMusicFadeOut": null,
  "enableObs": false,
  "enablePp": true,
  "enableVlcPlaylistCreation": null,
  "excludeLffi": null,
  "excludeLffiImages": null,
  "excludeTh": null,
  "hideMediaLogo": null,
  "keepOriginalsAfterConversion": null,
  "lang": "ASL",
  "langUpdatedLast": "2022-08-15T14:42:24.994Z",
  "localAppLang": "nl",
  "localOutputPath": "***",
  "maxRes": "720p",
  "musicFadeOutTime": null,
  "musicFadeOutType": null,
  "musicVolume": null,
  "mwDay": "4",
  "mwStartTime": "12:00",
  "obsCameraScene": "Media",
  "obsMediaScene": "Spreker",
  "obsPassword": "JW",
  "obsPort": "4444",
  "outputFolderDateFormat": "YYYY-MM-DD",
  "ppBackward": "PageUp",
  "ppForward": "PageDown",
  "preferredOutput": null,
  "weDay": "5",
  "weStartTime": "12:00"
}
```

### Error details
```
{
  "stack": "Error: Syntax error, unrecognized expression: #songPicker option: selected\n    at Sizzle.error (/tmp/.mount_M3.AppI95wcF/resources/app.asar/node_modules/jquery/dist/jquery.js:1681:8)\n    at Sizzle.tokenize (/tmp/.mount_M3.AppI95wcF/resources/app.asar/node_modules/jquery/dist/jquery.js:2381:11)\n    at Sizzle.select (/tmp/.mount_M3.AppI95wcF/resources/app.asar/node_modules/jquery/dist/jquery.js:2842:20)\n    at Function.Sizzle [as find] (/tmp/.mount_M3.AppI95wcF/resources/app.asar/node_modules/jquery/dist/jquery.js:898:9)\n    at jQuery.fn.init.find (/tmp/.mount_M3.AppI95wcF/resources/app.asar/node_modules/jquery/dist/jquery.js:3099:11)\n    at new jQuery.fn.init (/tmp/.mount_M3.AppI95wcF/resources/app.asar/node_modules/jquery/dist/jquery.js:3209:32)\n    at jQuery (/tmp/.mount_M3.AppI95wcF/resources/app.asar/node_modules/jquery/dist/jquery.js:161:10)\n    at HTMLButtonElement.<anonymous> (file:///tmp/.mount_M3.AppI95wcF/resources/app.asar/media-updater.js:1813:86)",
  "message": "Syntax error, unrecognized expression: #songPicker option: selected"
}
```

**Comment by sircharlo** [comment]
The problem was with one of my VSCode plugins, it added a space where it shouldn't! Can you try cloning the repo and seeing if it works now? Also, sign language should be a bit better supported now. Let me know 🙂

**Comment by mtdvlpr** [comment]
Works now!
