### ISSUE TITLE
[BUG] Media safenames not applied during JWPUB import

### ISSUE THREAD

**Issue by sircharlo** [sircharlo/meeting-media-manager#870]
**Describe the bug**
Media safenames not applied during JWPUB import, resulting in filenames being too long and not being saved properly

**To Reproduce**

1. Folder structure: `C:\Users\username\Videos\MMM\U\`
2. Click on any date tile to add media for that date
3. Add media from lesson 29 of the LFF JWPUB file
4. See error: `Error: ENOENT: no such file or directory, open 'C:/Users/username/Videos/MMM/E/2022-12-18/00-00 05 - Коллаж Обычаи связанные с почитанием умерших - 1 мужчина на коленях молится перед надгробным камнем возле которого расставлены приношения с едой - 2 трое мужчин в племенных костюмах неистово танцуют - 3 во время празднования Дня мёртвых люди несут на шестах большие черепа у всех на лицах маски в виде черепа.jpg'`

**Expected behavior**
The filename is clearly too long.

This is confirmed if trying to manually create a file named `00-00 05 - Коллаж Обычаи связанные с почитанием умерших - 1 мужчина на коленях молится перед надгробным камнем возле которого расставлены приношения с едой - 2 трое мужчин в племенных костюмах неистово танцуют - 3 во время празднования Дня мёртвых люди несут на шестах большие черепа у всех на лицах маски в виде черепа.jpg` in the target directory: Windows does not allow it and truncates the filename automatically.

JWPUB imported media filenames should therefore be truncated, just like other media filenames are truncated elsewhere in the app.

**Logs**
```
instrument.js:108 Error: ENOENT: no such file or directory, open 'C:/Users/sirch/Videos/MMM/E/2022-12-18/00-00 05 - Коллаж Обычаи связанные с почитанием умерших - 1 мужчина на коленях молится перед надгробным камнем возле которого расставлены приношения с едой - 2 трое мужчин в племенных костюмах неистово танцуют - 3 во время празднования Дня мёртвых люди несут на шестах большие черепа у всех на лицах маски в виде черепа.jpg'
    at Object.openSync (node:fs:594:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2207:35)
    at createFileSync (file.js:63:6)
    at f.<anonymous> (fs.ts:192:9)
    at f.processFile (add.vue?7509:243:14)
    at add.vue?7509:362:30
    at Array.forEach (<anonymous>)
    at f.saveFiles (add.vue?7509:361:15)
    at click (add.vue:4:5286)
    at Ue (vue.runtime.esm.js:3017:30)
    at f.n (vue.runtime.esm.js:1815:20)
    at Ue (vue.runtime.esm.js:3017:30)
    at t.$emit (vue.runtime.esm.js:3716:17)
    at f.click (VBtn.ts:163:12)
    at Ue (vue.runtime.esm.js:3017:30)
    at HTMLButtonElement.n (vue.runtime.esm.js:1815:20)
    at c._wrapper (vue.runtime.esm.js:7473:35)
    at HTMLButtonElement.r (helpers.js:90:17)
(anonymous) @ instrument.js:108
d @ logger.ts:33
warn @ logger.ts:44
(anonymous) @ notify.ts:74
(anonymous) @ fs.ts:195
processFile @ add.vue?7509:243
(anonymous) @ add.vue?7509:362
saveFiles @ add.vue?7509:361
click @ add.vue:4
Ue @ vue.runtime.esm.js:3017
n @ vue.runtime.esm.js:1815
Ue @ vue.runtime.esm.js:3017
t.$emit @ vue.runtime.esm.js:3716
click @ VBtn.ts:163
Ue @ vue.runtime.esm.js:3017
n @ vue.runtime.esm.js:1815
c._wrapper @ vue.runtime.esm.js:7473
r @ helpers.js:90
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1275666/208300965-02ea6184-3cdb-4c5b-9140-ae91cf7dd5a3.png)

**Comment by sircharlo** [comment]
I'll take this one, easy fix :)

**Comment by sircharlo** [comment]
Fixed in https://github.com/sircharlo/meeting-media-manager/commit/e7f64fd7b011ebffcce903088ee77186790ce933
